spring.application.name=order-processing-system

server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/order_system
spring.datasource.username=postgres
spring.datasource.password=106720Fr
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate settings (optional)
spring.jpa.hibernate.ddl-auto=update


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest